export interface Product {
  _id?: string;
  id?: number;
  productId?: string;
  name?: string;
  productName?: string;
  price?: number;
  productPrice?: string | number;
  mrp?: number;
  rating?: number;
  productReview?: number;
  reviews?: any[];
  productImage?: string[];
  badge?: string;
  isBestSeller?: boolean;
  emiText?: string;
  discount?: number;
  productDiscount?: number;
  discountPercentage?: number;
  category?: string;
  productType?: string;
  description?: string;
  fullDescription?: string;
  shortDescription?: string;
  productDescription?: string;
  stock?: number;
  productSlug?: string;
  slug?: string;
  images?: string[];
  image?: string;
  brand?: string;
  sku?: string;
  weight?: string;
  dimensions?: string;
  material?: string;
  warranty?: string;
  returnPolicy?: string;
  finalPrice?: number;
  colors?: string[];
  finishes?: string[];
  specifications?: Array<{ key: string; value: string }>;
  isVisible?: boolean;
  createdBy?: string;
  createdAt?: string;
  updatedAt?: string;
}
